== Version Control

Latest Version: 0.3.1

docker.io/laoluade/archive-ingestor:0.3.1

Note: Update ArchiveIngestor class and version table, package-info, pom.xml, docker file, and docker compose file when updating this value.

=== Changelog

[cols="1,1"]
|===

|Version 0.3.1
a| * Updated Angular settings to run a proxy during development.
* Modified all services to now receive their base ref from a single plain js class.
* Updated websocket configurations to allow connections from the angular development server.
* Cleaned up client-side error handling and logging on Angular front end.
* Fixed Angular bugs such as lapses in settings checks to ensure bad request aren't sent, hanging progress sections that don't allow users to try again.
* Improved front-end CSS to make application more user-friendly.
* Re-enabled prerendering and server-side rendering options during build process and fixed the bug preventing that earlier.
* Updated elements that display the total chapter count by making them display a TBD in place of a -1.
* Created a docker image and docker compose file using the selenium/hub:4.39.0 and selenium/node-chrome:143.0-20251212 images.
* Updated web page title and favicon.

|Version 0.3
a| * Updated ArchiveIngestor.filterText() to ignore bolded text and blank space.
* Created an ArchiveComment POJO and used it to update ArchiveChapter and ArchiveIngestor's comment parsing functionality.
* Added lines to print the exception stack trace if an unexpected error takes place in ArchiveIngestor.startCreateTask().
* Updated Angular frontend services to use document.location.pathname as a URL base instead of document.location.href.
* Simplified Angular comment data models into one single model that is in line with the ArchiveComment POJO and updated the chapter data model to use the unified comment model.
* Fixed bug in Angular result component where the latest chapter wasn't filtered from the rest by adding a dedicated latest chapter ID tracker.
* Simplified the Angular chapter, comment, and comment thread components using the new unified comment data model.

|Version 0.2.1
a| * First completed version of project.

|Version 0.1
a|* Initial project.
* Good for otwarchive v0.9.449.0.

|===
