package com.laoluade.ingestor.ao3.core;

import com.google.common.hash.Hashing;
import org.json.JSONArray;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 * <p>
 *     This class is a data model for AO3 story metadata.
 *     {@link ArchiveIngestor} uses this to store relevant story metadata.
 * </p>
 */
public class ArchiveStoryInfo {
    // Meta items - self created
    /**
     * <p>This attribute stores the time and date when the story object is created.</p>
     */
    public ZonedDateTime creationTimestamp;

    /**
     * <p>This attribute stores the unique SHA-256 generated by the story's information.</p>
     */
    public String creationHash;

    // Meta items - passed in
    /**
     * <p>This attribute stores the ratings assigned to the story.</p>
     */
    public ArrayList<String> ratings;

    /**
     * <p>This attribute stores the warnings assigned to the story.</p>
     */
    public ArrayList<String> warnings;

    /**
     * <p>This attribute stores the relationship categories assigned to the story.</p>
     */
    public ArrayList<String> categories;

    /**
     * <p>This attribute stores the fandoms assigned to the story.</p>
     */
    public ArrayList<String> fandoms;

    /**
     * <p>This attribute stores the relationships in the story.</p>
     */
    public ArrayList<String> relationships;

    /**
     * <p>This attribute stores the characters in the story.</p>
     */
    public ArrayList<String> characters;

    /**
     * <p>This attribute stores the additional tags assigned to the story.</p>
     */
    public ArrayList<String> additionalTags;

    /**
     * <p>This attribute stores the language of the story.</p>
     */
    public String language;

    /**
     * <p>This attribute stores the series the story is in.</p>
     */
    public ArrayList<String> series;

    /**
     * <p>This attribute stores the collections the story is in.</p>
     */
    public ArrayList<String> collections;

    /**
     * <p>This attribute stores when the story was published.</p>
     */
    public LocalDate published;

    /**
     * <p>This attribute stores the current status of the story.</p>
     */
    public String status;

    /**
     * <p>This attribute stores when the status of the story was last updated.</p>
     */
    public LocalDate statusWhen;

    /**
     * <p>This attribute stores the word count of the story.</p>
     */
    public Integer words;

    /**
     * <p>This attribute stores the current chapter count of the story.</p>
     */
    public Integer currentChapters;

    /**
     * <p>This attribute stores the total chapter count of the story.</p>
     */
    public Integer totalChapters;

    /**
     * <p>This attribute stores the comment count of the story.</p>
     */
    public Integer comments;

    /**
     * <p>This attribute stores the kudos count of the story.</p>
     */
    public Integer kudos;

    /**
     * <p>This attribute stores the bookmark count of the story.</p>
     */
    public Integer bookmarks;

    /**
     * <p>This attribute stores the hit count of the story.</p>
     */
    public Integer hits;

    // Preface items
    /**
     * <p>This attribute stores whether the story metadata has already been defined.</p>
     */
    public boolean isSet = false;

    /**
     * <p>This attribute stores the title of the story.</p>
     */
    public String title;

    /**
     * <p>This attribute stores the authors of the story.</p>
     */
    public ArrayList<String> authors;

    /**
     * <p>This attribute stores the summary of the story.</p>
     */
    public ArrayList<String> summary;

    /**
     * <p>This attribute stores the associations of the story.</p>
     */
    public ArrayList<String> associations;

    /**
     * <p>This attribute stores the starting notes of the story.</p>
     */
    public ArrayList<String> startNotes;

    /**
     * <p>This attribute stores the ending notes of the story.</p>
     */
    public ArrayList<String> endNotes;

    // Other information
    /**
     * <p>This attribute stores a list of registered users who have left kudos.</p>
     */
    public ArrayList<String> registeredKudos;

    /**
     * <p>
     *     This attribute stores how much unregistered kudos are left.
     *     Unregistered kudos can count as guest kudos are simply users who are not counted during the parsing process.
     * </p>
     */
    public Integer unregisteredKudos;

    /**
     * <p>This attribute stores a list of registered users who publicly bookmarked the story.</p>
     */
    public ArrayList<String> publicBookmarks;

    /**
     * <p>
     *     This attribute stores how much unregistered bookmarks are left.
     *     Unregistered kudos can count as private bookmarks or
     *     bookmarks that are simply not counted during the parsing process.
     * </p>
     */
    public Integer unregisteredBookmarks;

//    // Empty constructor for manual construction
//    /**
//     * <p>
//     *     This constructor is an empty constructor for manually creating the story metadata object.
//     *     This was created for a possible future when JSON objects are used to construct POJO instances
//     *     but is not in use right now.
//     * </p>
//     */
//    public ArchiveStoryInfo() {}

    // Default constructor for parsing needs
    /**
     * <p>This constructor is used to instantiate a story metadata object with initial information.</p>
     * @param ratings The ratings list parsed from the story link.
     * @param warnings The warnings list parsed from the story link.
     * @param categories The categories list parsed from the story link.
     * @param fandoms The fandoms list parsed from the story link.
     * @param relationships The relationships list parsed from the story link.
     * @param characters The characters list parsed from the story link.
     * @param additionalTags The additional tags list parsed from the story link.
     * @param language The language parsed from the story link.
     * @param series The series list parsed from the story link.
     * @param collections The collections list parsed from the story link.
     * @param published The publishing date parsed from the story link.
     * @param status The status parsed from the story link.
     * @param statusWhen The status update date parsed from the story link.
     * @param words The word count parsed from the story link.
     * @param chapters The chapter count parsed from the story link.
     * @param comments The comment count parsed from the story link.
     * @param kudos The kudos count parsed from the story link.
     * @param bookmarks The bookmark count parsed from the story link.
     * @param hits The hit count parsed from the story link.
     */
    public ArchiveStoryInfo(ArrayList<String> ratings,
                            ArrayList<String> warnings, ArrayList<String> categories, ArrayList<String> fandoms,
                            ArrayList<String> relationships, ArrayList<String> characters,
                            ArrayList<String> additionalTags, String language, ArrayList<String> series,
                            ArrayList<String> collections, String published, String status, String statusWhen, String words, String chapters,
                            String comments, String kudos, String bookmarks, String hits) {
        // Get current timestamp
        this.creationTimestamp = ZonedDateTime.now(ZoneId.of("UTC"));

        // Set core information
        this.ratings = ratings;
        this.warnings = warnings;
        this.categories = categories;
        this.fandoms = fandoms;
        this.relationships = relationships;
        this.characters = characters;
        this.additionalTags = additionalTags;
        this.language = language;
        this.series = new ArrayList<>(series.stream().filter(str -> !str.contains("Part")).toList());
        this.collections = collections;

        // Setup statistics
        this.published = LocalDate.parse(published);
        this.words = parseInitString(words);

        this.status = status.replace(":", "");
        if (!status.equals(ArchiveIngestor.PLACEHOLDER)) {
            this.statusWhen = LocalDate.parse(statusWhen);
        }
        else {
            this.statusWhen = LocalDate.now();
        }

        String[] chaptersSplit = chapters.split("/");
        this.currentChapters = parseInitString(chaptersSplit[0]);
        this.totalChapters = parseInitString(chaptersSplit[1]);

        this.comments = parseInitString(comments);
        this.kudos = parseInitString(kudos);
        this.bookmarks = parseInitString(bookmarks);
        this.hits = parseInitString(hits);
    }

    /**
     * <p>This method parses a string into an integer using class-specific rules.</p>
     * @param initString The number in string format.
     * @return The number as an integer.
     */
    public static Integer parseInitString(String initString) {
        if (initString.equals("?")) {
            return -1;
        }
        else if (!initString.equals(ArchiveIngestor.PLACEHOLDER)) {
            return Integer.parseInt(initString.replace(",", ""));
        }
        else {
            return 0;
        }
    }

    /**
     * <p>This method sets the preface-specific attributes of the story metadata object.</p>
     * @param title The parsed title of the story.
     * @param authors The parsed authors of the story.
     * @param summary The parsed summary of the story.
     * @param associations The parsed associations of the story.
     * @param startNotes The parsed starting notes of the story.
     * @param endNotes The parsed ending notes of the story.
     */
    public void setPrefaceInfo(String title, ArrayList<String> authors, ArrayList<String> summary,
                               ArrayList<String> associations, ArrayList<String> startNotes,
                               ArrayList<String> endNotes) {
        // Set preface values
        this.title = title;
        this.authors = authors;
        this.summary = summary;
        this.startNotes = startNotes;
        this.endNotes = endNotes;

        // Filter association list before setting
        this.associations = new ArrayList<>();
        for (String association : associations) {
            if (association.contains("For")) {
                this.associations.add(association);
            }
            else if (association.contains("translation")) {
                this.associations.add(association);
            }
        }

        // Generate the hash using preface information
        String creationHashInput = this.title + String.join("", this.authors) +
                String.join("", this.summary) + String.join("", this.associations) +
                String.join("", this.startNotes) + String.join("", this.endNotes);
        this.creationHash = Hashing.sha256().hashString(creationHashInput, StandardCharsets.UTF_8).toString();
    }

    /**
     * <p>
     *     This method sets the<code>registeredKudos</code> and <code>unregisteredKudos</code>
     *     attributes of the story metadata object.
     * </p>
     * @param kudosList The parsed list of users who left kudos.
     */
    public void setKudosList(ArrayList<String> kudosList) {
        this.registeredKudos = kudosList;
        this.unregisteredKudos = this.kudos - this.registeredKudos.size();
    }

    /**
     * <p>
     *     This method sets the<code>publicBookmarks</code> and <code>unregisteredBookmarks</code>
     *     attributes of the story metadata object.
     * </p>
     * @param bookmarkList The parsed list of users who left public bookmarks.
     */
    public void setPublicBookmarkList(ArrayList<String> bookmarkList) {
        this.publicBookmarks = bookmarkList;
        this.unregisteredBookmarks = this.bookmarks - this.publicBookmarks.size();
    }

    /**
     * <p>This method retrieves a {@link JSONObject} representation of the story metadata.</p>
     * @return {@link JSONObject} representation of the story metadata.
     */
    public JSONObject getJSONRep() {
        JSONObject rep = new JSONObject();
        rep.put("creationTimestamp", this.creationTimestamp.toString());
        rep.put("creationHash", this.creationHash);
        rep.put("ratings", new JSONArray(this.ratings));
        rep.put("warnings", new JSONArray(this.warnings));
        rep.put("categories", new JSONArray(this.categories));
        rep.put("fandoms", new JSONArray(this.fandoms));
        rep.put("relationships", new JSONArray(this.relationships));
        rep.put("characters", new JSONArray(this.characters));
        rep.put("additionalTags", new JSONArray(this.additionalTags));
        rep.put("language", this.language);
        rep.put("series", new JSONArray(this.series));
        rep.put("collections", new JSONArray(this.collections));
        rep.put("published", this.published.toString());
        rep.put("status", this.status);
        rep.put("statusWhen", this.statusWhen.toString());
        rep.put("words", this.words);
        rep.put("currentChapters", this.currentChapters);
        rep.put("totalChapters", this.totalChapters);
        rep.put("comments", this.comments);
        rep.put("kudos", this.kudos);
        rep.put("bookmarks", this.bookmarks);
        rep.put("hits", this.hits);
        rep.put("title", this.title);
        rep.put("authors", new JSONArray(this.authors));
        rep.put("summary", new JSONArray(this.summary));
        rep.put("associations", new JSONArray(this.associations));
        rep.put("startNotes", new JSONArray(this.startNotes));
        rep.put("endNotes", new JSONArray(this.endNotes));
        rep.put("registeredKudos", new JSONArray(this.registeredKudos));
        rep.put("unregisteredKudos", this.unregisteredKudos);
        rep.put("publicBookmarks", new JSONArray(this.publicBookmarks));
        rep.put("unregisteredBookmarks", this.unregisteredBookmarks);
        return rep;
    }

//    /**
//     * <p>This method converts a {@link JSONArray} to a {@link ArrayList} of strings.</p>
//     * <p>This was created for a possible future when JSON objects are used to construct POJO instances but not now.</p>
//     * @param oldJSONArray The JSON array to convert.
//     * @return {@link ArrayList} of strings.
//     */
//    public static ArrayList<String> convertJSONArrayToArrayList(JSONArray oldJSONArray) {
//        ArrayList<String> newArrayList = new ArrayList<>();
//        for (int i = 0; i < oldJSONArray.length(); i++) {
//            newArrayList.add(oldJSONArray.getString(i));
//        }
//        return newArrayList;
//    }
//
//    /**
//     * <p>This static method creates a story metadata object from a JSON String.</p>
//     * <p>This was created for a possible future when JSON objects are used to construct POJO instances but not now.</p>
//     * @param jsonString The JSON string to convert.
//     * @return A new story metadata object.
//     */
//    public static ArchiveStoryInfo fromJSONString(String jsonString) {
//        JSONObject newStoryInfoJSON = new JSONObject(jsonString);
//        ArchiveStoryInfo newArchiveStoryInfo = new ArchiveStoryInfo();
//
//        newArchiveStoryInfo.creationTimestamp = ZonedDateTime.parse(newStoryInfoJSON.getString("creationTimestamp"));
//        newArchiveStoryInfo.creationHash = newStoryInfoJSON.getString("creationHash");
//        newArchiveStoryInfo.ratings = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("ratings"));
//        newArchiveStoryInfo.warnings = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("warnings"));
//        newArchiveStoryInfo.categories = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("categories"));
//        newArchiveStoryInfo.fandoms = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("fandoms"));
//        newArchiveStoryInfo.relationships = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("relationships"));
//        newArchiveStoryInfo.characters = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("characters"));
//        newArchiveStoryInfo.additionalTags = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("additionalTags"));
//        newArchiveStoryInfo.language = newStoryInfoJSON.getString("language");
//        newArchiveStoryInfo.series = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("series"));
//        newArchiveStoryInfo.collections = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("collections"));
//        newArchiveStoryInfo.published = LocalDate.parse(newStoryInfoJSON.getString("published"));
//        newArchiveStoryInfo.status = newStoryInfoJSON.getString("status");
//        newArchiveStoryInfo.statusWhen = LocalDate.parse(newStoryInfoJSON.getString("statusWhen"));
//        newArchiveStoryInfo.words = newStoryInfoJSON.getInt("words");
//        newArchiveStoryInfo.currentChapters = newStoryInfoJSON.getInt("currentChapters");
//        newArchiveStoryInfo.totalChapters = newStoryInfoJSON.getInt("totalChapters");
//        newArchiveStoryInfo.comments = newStoryInfoJSON.getInt("comments");
//        newArchiveStoryInfo.kudos = newStoryInfoJSON.getInt("kudos");
//        newArchiveStoryInfo.bookmarks = newStoryInfoJSON.getInt("bookmarks");
//        newArchiveStoryInfo.hits = newStoryInfoJSON.getInt("hits");
//        newArchiveStoryInfo.title = newStoryInfoJSON.getString("title");
//        newArchiveStoryInfo.authors = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("authors"));
//        newArchiveStoryInfo.summary = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("summary"));
//        newArchiveStoryInfo.associations = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("associations"));
//        newArchiveStoryInfo.startNotes = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("startNotes"));
//        newArchiveStoryInfo.endNotes = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("endNotes"));
//        newArchiveStoryInfo.registeredKudos = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("registeredKudos"));
//        newArchiveStoryInfo.unregisteredKudos = newStoryInfoJSON.getInt("unregisteredKudos");
//        newArchiveStoryInfo.publicBookmarks = convertJSONArrayToArrayList(newStoryInfoJSON.getJSONArray("publicBookmarks"));
//        newArchiveStoryInfo.unregisteredBookmarks = newStoryInfoJSON.getInt("unregisteredBookmarks");
//
//        return newArchiveStoryInfo;
//    }
}
