package com.laoluade.ingestor.ao3.core;

import com.google.common.hash.Hashing;
import org.json.JSONArray;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;

/**
 * <p>
 *     This class is a data model for an AO3 story.
 *     {@link ArchiveIngestor} uses this to store relevant story information over time.
 * </p>
 */
public class ArchiveStory {
    // Meta items - self created
    /**
     * <p>This attribute stores the time and date when the story object is created.</p>
     */
    public ZonedDateTime creationTimestamp;

    /**
     * <p>This attribute stores the unique SHA-256 generated by the story's information.</p>
     */
    public String creationHash;

    // Meta items - passed in
    /**
     * <p>This attribute stores the {@link ArchiveStoryInfo} object representing story metadata.</p>
     */
    public ArchiveStoryInfo archiveStoryInfo;

    /**
     * <p>This attribute stores an {@link ArrayList} of {@link ArchiveChapter} objects.</p>
     */
    public ArrayList<ArchiveChapter> archiveChapters;

    /**
     * <p>This constructor creates a story object with story metadata and chapter information.</p>
     * @param archiveStoryInfo The parsed story metadata.
     * @param archiveChapters The parsed chapters.
     */
    public ArchiveStory(ArchiveStoryInfo archiveStoryInfo, ArrayList<ArchiveChapter> archiveChapters) {
        // Get current timestamp
        this.creationTimestamp = ZonedDateTime.now(ZoneId.of("UTC"));

        // Set information
        this.archiveStoryInfo = archiveStoryInfo;
        this.archiveChapters = archiveChapters;

        // Generate the hash using hashes from story information and chapters
        String chapterHashes = "";
        for (ArchiveChapter archiveChapter : this.archiveChapters) {
            chapterHashes = chapterHashes + archiveChapter.creationHash;
        }
        String creationHashInput = this.archiveStoryInfo.creationHash + chapterHashes;
        this.creationHash = Hashing.sha256().hashString(creationHashInput, StandardCharsets.UTF_8).toString();
    }

    /**
     * <p>This method retrieves a {@link JSONObject} representation of the story.</p>
     * @return {@link JSONObject} representation of the story.
     */
    public JSONObject getJSONRep() {
        JSONArray chapterJSONs = new JSONArray();
        for (ArchiveChapter archiveChapter : this.archiveChapters) {
            chapterJSONs.put(archiveChapter.getJSONRepWithoutParent());
        }

        JSONObject rep = new JSONObject();
        rep.put("creationTimestamp", this.creationTimestamp.toString());
        rep.put("creationHash", this.creationHash);
        rep.put("archiveStoryInfo", this.archiveStoryInfo.getJSONRep());
        rep.put("archiveChapters", chapterJSONs);
        return rep;
    }
}
