package com.laoluade.ingestor.ao3.core;

import com.google.common.hash.Hashing;
import org.json.JSONArray;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;

// TODO: Add tests for this
/**
 * <p>
 *     This class is a data model for an AO3 comment.
 *     {@link ArchiveIngestor} uses this to store relevant comment information.
 * </p>
 */
public class ArchiveComment {
    // Meta items - self created
    /**
     * <p>This attribute stores the time and date when the story object is created.</p>
     */
    public ZonedDateTime creationTimestamp;

    /**
     * <p>This attribute stores the unique SHA-256 generated by the story's information.</p>
     */
    public String creationHash;

    // Meta items - passed in
    /**
     * <p>This attribute stores the user that posted the comment.</p>
     */
    public String user;

    /**
     * <p>This attribute stores the date and time the comment was posted.</p>
     */
    public String posted;

    /**
     * <p>This attribute stores the actual text of the comment.</p>
     */
    public ArrayList<String> text;

    /**
     * <p>This attribute stores how deep the comment is in a thread of replies.</p>
     */
    public Integer depth;

    /**
     * <p>This attribute stores the page number the comment was found on.</p>
     */
    public Integer page;

    /**
     * <p>This attribute stores the replies the comment has.</p>
     */
    public ArrayList<ArchiveComment> replies = new ArrayList<>();

    /**
     * <p>This constructor starts a comment object.</p>
     * @param user The user that posted the comment.
     * @param posted The date and time the comment was posted.
     * @param text The actual text of the comment.
     * @param depth How deep the comment is in a thread of replies.
     * @param page The page number the comment was found on.
     */
    public ArchiveComment(String user, String posted, ArrayList<String> text, Integer depth, Integer page) {
        // Get current timestamp
        this.creationTimestamp = ZonedDateTime.now(ZoneId.of("UTC"));

        // Set comment information
        this.user = user;
        this.posted = posted;
        this.text = text;
        this.depth = depth;
        this.page = page;

        // Generate the hash using comment information
        String creationHashInput = this.user + this.posted + String.join("", this.text) + this.depth + this.page;
        this.creationHash = Hashing.sha256().hashString(creationHashInput, StandardCharsets.UTF_8).toString();
    }

    /**
     * <p>This method sets the <code>replies</code> attribute of the comment.</p>
     * @param replies
     */
    public void setReplies(ArrayList<ArchiveComment> replies) {
        this.replies = replies;
    }

    /**
     * <p>This static method converts an arraylist of archive comments to JSON format.</p>
     * @param commentArray The arraylist of archive comments.
     * @return A JSON representation of a list of comments.
     */
    public static JSONArray convertCommentArrayListToJSON(ArrayList<ArchiveComment> commentArray) {
        JSONArray commentJSON = new JSONArray();
        for (ArchiveComment comment : commentArray) {
            commentJSON.put(comment.getJSONRep());
        }
        return commentJSON;
    }

    /**
     * <p>This method retrieves a {@link JSONObject} representation of the comment.</p>
     * @return {@link JSONObject} representation of the comment.
     */
    public JSONObject getJSONRep() {
        JSONObject rep = new JSONObject();
        rep.put("creationTimestamp", this.creationTimestamp.toString());
        rep.put("creationHash", this.creationHash);
        rep.put("user", this.user);
        rep.put("posted", this.posted);
        rep.put("text", new JSONArray(this.text));
        rep.put("depth", this.depth);
        rep.put("page", this.page);
        rep.put("replies", convertCommentArrayListToJSON(this.replies));

        return rep;
    }
}
