package com.laoluade.ingestor.ao3.core;

import com.google.common.hash.Hashing;
import org.json.JSONArray;
import org.json.JSONObject;

import java.nio.charset.StandardCharsets;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;

/**
 * <p>
 *     This class is a data model for an AO3 chapter.
 *     {@link ArchiveIngestor} uses this to store relevant chapter information over time.
 * </p>
 */
public class ArchiveChapter {
    // Meta items - self created
    /**
     * <p>This attribute stores the time and date when the chapter object is created.</p>
     */
    public ZonedDateTime creationTimestamp;

    /**
     * <p>This attribute stores the unique SHA-256 generated by the chapter's information.</p>
     */
    public String creationHash;

    // Meta items - passed in
    /**
     * <p>This attribute stores the parent {@link ArchiveStoryInfo} object representing story metadata.</p>
     */
    public ArchiveStoryInfo parentArchiveStoryInfo;

    /**
     * <p>This attribute stores the title of the page where the chapter was parsed.</p>
     */
    public String pageTitle;

    /**
     * <p>This attribute stores the web link of the page where the chapter was parsed.</p>
     */
    public String pageLink;

    /**
     * <p>This attribute stores the title of the chapter.</p>
     */
    public String chapterTitle;

    /**
     * <p>This attribute stores the summary of the chapter.</p>
     */
    public ArrayList<String> summary;

    /**
     * <p>This attribute stores the starting notes of the chapter.</p>
     */
    public ArrayList<String> startNotes;

    /**
     * <p>This attribute stores the ending notes of the chapter.</p>
     */
    public ArrayList<String> endNotes;

    /**
     * <p>This attribute stores the paragraph text of the chapter.</p>
     */
    public ArrayList<String> paragraphs;

    /**
     * <p>This attribute stores the comment threads of the chapter.</p>
     */
    public ArrayList<ArchiveComment> foundComments;

    /**
     * <p>
     *     This constructor initializes the chapter object using
     *     information retrieved early in the archive parsing process.
     *     The creation timestamp and hash is based off of this information.
     * </p>
     * @param parentArchiveStoryInfo The {@link ArchiveStoryInfo} holding the story metadata.
     * @param pageTitle The parsed title of the page from the browser.
     * @param chapterTitle The parsed (or autogenerated) chapter title.
     * @param summary The parsed chapter summary (or an empty {@link ArrayList}).
     * @param startNotes The parsed chapter starting notes (or an empty {@link ArrayList}).
     * @param endNotes The parsed chapter ending notes (or an empty {@link ArrayList}).
     * @param paragraphs The parsed chapter text (it BETTER not be an empty {@link ArrayList}).
     */
    public ArchiveChapter(ArchiveStoryInfo parentArchiveStoryInfo, String pageTitle, String chapterTitle, ArrayList<String> summary,
                          ArrayList<String> startNotes, ArrayList<String> endNotes, ArrayList<String> paragraphs) {
        // Get current timestamp
        this.creationTimestamp = ZonedDateTime.now(ZoneId.of("UTC"));

        // Set parent story
        this.parentArchiveStoryInfo = parentArchiveStoryInfo;

        // Set chapter information
        this.pageTitle = pageTitle;
        this.chapterTitle = chapterTitle;
        this.summary = summary;
        this.startNotes = startNotes;
        this.endNotes = endNotes;
        this.paragraphs = paragraphs;

        // Generate the hash using chapter information except for paragraphs
        String creationHashInput = this.chapterTitle + String.join("", this.summary) +
                String.join("", this.startNotes) + String.join("", this.endNotes) +
                this.parentArchiveStoryInfo.creationHash;
        this.creationHash = Hashing.sha256().hashString(creationHashInput, StandardCharsets.UTF_8).toString();
    }

    /**
     * <p>This method sets the <code>pageLink</code> attribute of the object.</p>
     * @param pageLink The link where the chapter was parsed from (gotten through Selenium).
     */
    public void setPageLink(String pageLink) {
        this.pageLink = pageLink;
    }

    /**
     * <p>This method sets the <code>foundComments</code> attribute of the object.</p>
     * @param foundComments The JSONObject of comment threads.
     */
    public void setFoundComments(ArrayList<ArchiveComment> foundComments) {
        this.foundComments = foundComments;
    }

    /**
     * <p>
     *     This method retrieves a {@link JSONObject} representation of the chapter with the
     *     <code>parentArchiveStoryInfo</code> attribute included.
     * </p>
     * @return {@link JSONObject} representation of the chapter with the story metadata.
     */
    public JSONObject getJSONRepWithParent() {
        JSONObject rep = new JSONObject();
        rep.put("creationTimestamp", this.creationTimestamp.toString());
        rep.put("creationHash", this.creationHash);
        rep.put("parentArchiveStoryInfo", this.parentArchiveStoryInfo.getJSONRep());
        rep.put("pageTitle", this.pageTitle);
        rep.put("pageLink", this.pageLink);
        rep.put("chapterTitle", this.chapterTitle);
        rep.put("summary", new JSONArray(this.summary));
        rep.put("startNotes", new JSONArray(this.startNotes));
        rep.put("endNotes", new JSONArray(this.endNotes));
        rep.put("paragraphs", new JSONArray(this.paragraphs));
        rep.put("foundComments", ArchiveComment.convertCommentArrayListToJSON(this.foundComments));
        return rep;
    }

    /**
     * <p>
     *     This method retrieves a {@link JSONObject} representation of the chapter without the
     *     <code>parentArchiveStoryInfo</code> attribute.
     * </p>
     * @return {@link JSONObject} representation of the chapter without the story metadata.
     */
    public JSONObject getJSONRepWithoutParent() {
        JSONObject rep = new JSONObject();
        rep.put("creationTimestamp", this.creationTimestamp.toString());
        rep.put("creationHash", this.creationHash);
        rep.put("pageTitle", this.pageTitle);
        rep.put("pageLink", this.pageLink);
        rep.put("chapterTitle", this.chapterTitle);
        rep.put("summary", new JSONArray(this.summary));
        rep.put("startNotes", new JSONArray(this.startNotes));
        rep.put("endNotes", new JSONArray(this.endNotes));
        rep.put("paragraphs", new JSONArray(this.paragraphs));
        rep.put("foundComments", ArchiveComment.convertCommentArrayListToJSON(this.foundComments));
        return rep;
    }
}
